Add get api counter news by slug
jabardigitalservice/portal-jabar-services pull request #266
Opened 2022-08-18 09:54 UTC by rachadiannovansyah

Overview
- Add get counter views API
- Change the key of Redis

Evidence
project: Portal Jabar
title: Mengubah key redis dan menambahkankan get api counter
participants: @rachadiannovansyah

2022-08-18 10:04 UTC, rindibudiaramdhan approved these changes
ada Unit Test nya ga kang @rachadiannovansyah ?

2022-08-18 10:45 UTC, rindibudiaramdhan commented on core-service/src/modules/news/delivery/http/public_news_handler.go
> +	p.GET("/news/slug/:slug/view", handler.GetViewsBySlug)
bedanya GetBySlug dan GetViewsBySlug apa ya kang ?

2022-08-19 01:42 UTC, ayocodingit requested changes

2022-08-19 01:49 UTC, rachadiannovansyah commented on core-service/src/modules/news/delivery/http/public_news_handler.go
> +	p.GET("/news/slug/:slug/view", handler.GetViewsBySlug)
ini untuk nge-get views nya aja sekaligus jadi counter kang, karna yg GetBySlug jika kena memory-cache dia jadi issue ketika counting nya (jadi gajalan karna get data dari redis bukan dari sql nya)

2022-08-19 01:58 UTC, rachadiannovansyah commented on core-service/src/modules/news/delivery/http/public_news_handler.go
> +		"views": res.Views,
nice idea got an other step, here we go man [8136eb9](https://github.com/jabardigitalservice/portal-jabar-services/pull/266/commits/8136eb922826eb4df9da69ac1567624b1452b82f)

2022-08-19 02:00 UTC, ayocodingit approved these changes

2022-08-19 02:00 UTC, rachadiannovansyah commented on core-service/src/modules/news/delivery/http/public_news_handler.go
> +	p.GET("/news/slug/:slug/view", handler.GetViewsBySlug)
btw ini unit test nya menyusul kang, kejar target dlu 🤣

2022-08-19 02:01 UTC, ayocodingit commented on core-service/src/modules/news/delivery/http/public_news_handler.go
> +		"views": res.Views,
iya karena emng aku liat itu fail logic van wkwkw

2022-08-19 02:18 UTC, merged