adjust using parameterized queries
jabardigitalservice/portal-jabar-services pull request #267
Opened 2022-08-21 14:21 UTC by rachadiannovansyah

Overview:
Mitigation sql injection
- no longer using `sprintf` for formatting input
- now using parameterized queries

source of ref: https://www.stackhawk.com/blog/golang-sql-injection-guide-examples-and-prevention/

cc: @jabardigitalservice/jds-backend 

Evidence:
project: Portal Jabar
title: mitigasi SQL injection news module
participants: @rachadiannovansyah

2022-08-22 00:32 UTC, rindibudiaramdhan reviewed
kenapa func `findOne()` nya dihapus kang @rachadiannovansyah ?
saya lihat func tersebut memperbaiki duplikasi, dan sekarang dihilangkan.

permasalahannya bukannya di `sprintf` yang tidak akan dipakai lagi kan ya?

2022-08-23 03:04 UTC, rachadiannovansyah commented
> kenapa func `findOne()` nya dihapus kang @rachadiannovansyah ? saya lihat func tersebut memperbaiki duplikasi, dan sekarang dihilangkan.
> 
> permasalahannya bukannya di `sprintf` yang tidak akan dipakai lagi kan ya?

Kang @rindibudiaramdhan updated new commits ya, so now params are filtered using regex to a certain value is clean.

2022-08-23 06:30 UTC, rindibudiaramdhan requested changes
punten, kang. gatel euy ada if else teh. kalau suggest saya ada issue ga ya?

2022-08-23 06:30 UTC, rindibudiaramdhan commented on core-service/src/helpers/getters.go
> +		sortOrder = sortOrderValue[stringIndex]
```suggestion
sortOrder = sortOrderValue[stringIndex]
	if !stringExist {
 		sortOrder = "DESC"
```

2022-08-23 07:41 UTC, rachadiannovansyah commented on core-service/src/helpers/getters.go
> +		sortOrder = sortOrderValue[stringIndex]
amaaan, sudah di optimasi disini kang sekalian ada penambahan helpers https://github.com/jabardigitalservice/portal-jabar-services/pull/267/commits/da9da8d8243aaad2e71ef8a2d31f5c27bd40e30d

2022-08-23 07:59 UTC, ayocodingit approved these changes
aku liat udah ini aman, filter nya udh di sanitasi yah kang @rachadiannovansyah?, nanti nitip di bantu double check sama QA yah

2022-08-23 08:03 UTC, rachadiannovansyah commented
> aku liat udah ini aman, filter nya udh di sanitasi yah kang @rachadiannovansyah?, nanti nitip di bantu double check sama QA yah

yes sudah, binding dari params sudah aman di exec di repo nanti nya. Siaaap mang 👍

2022-08-23 09:31 UTC, merged

2022-08-23 12:32 UTC, rindibudiaramdhan approved these changes