Module Document Archive
jabardigitalservice/portal-jabar-services pull request #268
Opened 2022-08-25 08:15 UTC by rachadiannovansyah

Overview:
Add New Module Document Archive

Changes:
- add new column migration `document_archives` table
- add new modules list documents archive

cc: @jabardigitalservice/jds-backend 

Evidence
project: Portal Jabar
title: Menambahkan modul list arsip dan dokumen
participants: @rachadiannovansyah

2022-08-25 08:59 UTC, sandisunandar99 requested changes
nitip

2022-08-25 08:59 UTC, sandisunandar99 commented on core-service/src/database/migrations/20220825022241_create_document_archives_table.up.sql
> +    id INT(10) NOT NULL AUTO_INCREMENT,
pak kalo boleh masukan,, bisa jadi pertimbangan terkait pemakaian id di bandingkan dengan uuid.
referensi lumayan ciamik terutama terkait scure dan performace juga (walaupun ga gede2 pisan sih beda nya)

btw mungkin termasuk ke tabel yg lain juga ya kalo misalkan jadi pertimbangan

https://www.davidangulo.xyz/advantages-and-disadvantages-of-uuid/

2022-08-25 08:59 UTC, sandisunandar99 commented on core-service/src/modules/document-archive/repository/mysql/mysql_document_archive.go
> +	WHERE 1=1`
pak ini munkin bisa di hilangkan ya yang `WHERE 1=1` karna ini bisa nge baypass atau nge blind sql .. kurang lebih reference nya bisa disini

https://owasp.org/www-community/attacks/SQL_Injection_Bypassing_WAF

atau kalo mau kondisi where clause ke panggil ketika ada parameter yg kondisi true misal

 var sWhere string;
 sWhere = "Where"
 
 if (var == true){
    sWhere += "var = 1";
 }

2022-08-25 08:59 UTC, sandisunandar99 commented on core-service/src/database/migrations/20220825022241_create_document_archives_table.up.sql
> +    id INT(10) NOT NULL AUTO_INCREMENT,
yg ini mah tentatip aja ya,, mau d pake atau enga monggo aja,, 😆

2022-08-26 00:52 UTC, ayocodingit commented on core-service/src/database/migrations/20220825022241_create_document_archives_table.up.sql
> +    id INT(10) NOT NULL AUTO_INCREMENT,
Setuju mang, sekiranya bukan data master bagusnya menggunakan uuid, data master yang sifatnya unik juga menyangkut perusahaan/kredential sebaiknya menggunakan uuid, 😁

2022-08-26 04:18 UTC, rachadiannovansyah commented on core-service/src/database/migrations/20220825022241_create_document_archives_table.up.sql
> +    id INT(10) NOT NULL AUTO_INCREMENT,
waaah nuhun2 kangs menarik untuk diskusinya 😁 
yes beberapa di IPJ pun sudah ada yg menggunakan uuid sebagai unique primary key nya, salah satunya di module users, alasan kuat nya karna:
- perlu extra unique dan secure agar data users tidak mudah dibaca dan ditebak
- terlepas kalo users dikasih id increment bisa di looping juga kan sama orang iseng / hacker buat retrieved data nya, sedangkan kalo pake uuid perlu kombinasi character dgn pola khusus buat coba membacanya.

untuk module ini sebelumnya pun sempet terlintas juga pakai UUID,
namun ada beberapa pertimbangan kenapa saya memutuskan untuk tidak menggunakannya:
- cukup sulit untuk dilakukan sorting
- tidak memerlukan extra `unique` primary key
- cukup mahal di kantong storage DB jika tidak benar2 perlu menggunakannya
- sulit diingat ketika debugging 🤣 (ini becanda sih wkwk)

cc: kang @sandisunandar99 @ayocodingit 😁 🙏

2022-08-26 04:27 UTC, rachadiannovansyah commented on core-service/src/modules/document-archive/repository/mysql/mysql_document_archive.go
> +	WHERE 1=1`
waaah ini menarikk, related mitigasi sql injection yg kemarin ya..
overthinking dulu dan saya baca setelah jumatan ya kang sandi @sandisunandar99 🤣

2022-08-29 02:53 UTC, rachadiannovansyah commented on core-service/src/modules/document-archive/repository/mysql/mysql_document_archive.go
> +	WHERE 1=1`
kang @sandisunandar99 aku nangkap maksudnya, barusan aku coba2 ternyata cukup panjang juga jika pakai solusi itu, perlu melakukan 1-1 pengecekan tiap variabel params filter (misal: 1 modul ada 7 filter params, harus dicek 1-1 hingga nilai return bernilai true/false.
kayanya dengan solusi lain yg dilakukan untuk menghandle ini menggunakan cara:
- filterisasi di params dan di request body -> ini udah done
- menggunakan parameterized queries -> ref: https://www.stackhawk.com/blog/golang-sql-injection-guide-examples-and-prevention (ini akan digunakan ketika store a rows ke database)

2022-08-29 05:34 UTC, sandisunandar99 commented on core-service/src/modules/document-archive/repository/mysql/mysql_document_archive.go
> +	WHERE 1=1`
nah betul ,, jadi effort,, ini balik lagi ke developer nya sih mang,,, kalo dari saya hanya saran sih,, tapi kalo pun misalkan ada package/tool yang bisa membantu untuk itu contoh seprti Joi boleh sih ,, 😁 
#soryiklandikit 🤣

2022-08-29 05:46 UTC, ayocodingit commented on core-service/src/modules/document-archive/repository/mysql/mysql_document_archive.go
> +	WHERE 1=1`
jadi simple nya mah,  where 1=1 ini akan digunakan ketika terdapat salah satu filter yang dikirim dari frontend 😄

2022-08-29 08:33 UTC, ayocodingit approved these changes

2022-08-29 08:34 UTC, sandisunandar99 approved these changes

2022-08-29 09:04 UTC, rachadiannovansyah commented on core-service/src/modules/document-archive/repository/mysql/mysql_document_archive.go
> +	WHERE 1=1`
wkwk siaaaap noted mang @sandisunandar99 @ayocodingit 👍 👍

2022-08-29 09:11 UTC, merged